In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv("/content/coral_cleaned.csv")
df.head()

Latitude_Degrees  Longitude_Degrees Ocean_Name      Country_Name  \
0            23.163           -82.5260   Atlantic              Cuba   
1           -17.575          -149.7833    Pacific  French Polynesia   
2            18.369           -64.5640   Atlantic    United Kingdom   
3            17.760           -64.5680   Atlantic     United States   
4            17.769           -64.5830   Atlantic     United States   

  Temperature Stress Anomalies Frequency Max  \
0                                          5   
1                                          4   
2                                          7   
3                                          4   
4                                          5   

  Temperature Stress Anomalies Frequency Mean  \
0                                           0   
1                                           0   
2                                           0   
3                                           0   
4                                           0   

  Temperature Stress Anomalies Degree Heating Weeks  \
0                                                 0   
1                                              0.26   
2                                                 0   
3                                                 0   
4                                                 0   

  Temperature Stress Anomalies Degree Heating Weeks Maximum  \
0                                               7.25          
1                                               4.65          
2                                              11.66          
3                                               5.64          
4                                               6.89          

  Temperature Stress Anomalies Degree Heating Weeks Mean Bleaching Comments  
0                                               0.18                     nd  
1                                               0.19                     nd  
2                                               0.26                     nd  
3                                                0.2                     nd  
4                                               0.25                     nd

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41361 entries, 0 to 41360
Data columns (total 10 columns):
 #   Column                                                     Non-Null Count  Dtype  
---  ------                                                     --------------  -----  
 0   Latitude_Degrees                                           41361 non-null  float64
 1   Longitude_Degrees                                          41361 non-null  float64
 2   Ocean_Name                                                 41361 non-null  object 
 3   Country_Name                                               41361 non-null  object 
 4   Temperature Stress Anomalies Frequency Max                 41361 non-null  object 
 5   Temperature Stress Anomalies Frequency Mean                41361 non-null  object 
 6   Temperature Stress Anomalies Degree Heating Weeks          41361 non-null  object 
 7   Temperature Stress Anomalies Degree Heating Weeks Maximum  41361 non-null  object 
 8   Temper

In [6]:
numeric_columns = ["Temperature Stress Anomalies Frequency Max", "Temperature Stress Anomalies Frequency Mean", "Temperature Stress Anomalies Degree Heating Weeks", "Temperature Stress Anomalies Degree Heating Weeks Maximum", "Temperature Stress Anomalies Degree Heating Weeks Mean"]
df[numeric_columns] = df[numeric_columns].apply(pd.to_numeric, errors='coerce')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41361 entries, 0 to 41360
Data columns (total 10 columns):
 #   Column                                                     Non-Null Count  Dtype  
---  ------                                                     --------------  -----  
 0   Latitude_Degrees                                           41361 non-null  float64
 1   Longitude_Degrees                                          41361 non-null  float64
 2   Ocean_Name                                                 41361 non-null  object 
 3   Country_Name                                               41361 non-null  object 
 4   Temperature Stress Anomalies Frequency Max                 41229 non-null  float64
 5   Temperature Stress Anomalies Frequency Mean                41229 non-null  float64
 6   Temperature Stress Anomalies Degree Heating Weeks          41213 non-null  float64
 7   Temperature Stress Anomalies Degree Heating Weeks Maximum  41229 non-null  float64
 8   Temper

In [8]:
df.isnull().sum()

Latitude_Degrees                                               0
Longitude_Degrees                                              0
Ocean_Name                                                     0
Country_Name                                                   0
Temperature Stress Anomalies Frequency Max                   132
Temperature Stress Anomalies Frequency Mean                  132
Temperature Stress Anomalies Degree Heating Weeks            148
Temperature Stress Anomalies Degree Heating Weeks Maximum    132
Temperature Stress Anomalies Degree Heating Weeks Mean       132
Bleaching Comments                                             0
dtype: int64

In [9]:
df.describe()

Latitude_Degrees  Longitude_Degrees  \
count      41361.000000       41361.000000   
mean           7.558085          34.966127   
std           15.732185         103.404598   
min          -30.262500        -179.974300   
25%           -4.902500         -78.385600   
50%           10.776100          96.843300   
75%           20.050500         120.880400   
max           36.750000         179.964500   

       Temperature Stress Anomalies Frequency Max  \
count                                41229.000000   
mean                                     8.277684   
std                                      4.389347   
min                                      0.000000   
25%                                      5.750000   
50%                                      7.000000   
75%                                      9.330000   
max                                     52.000000   

       Temperature Stress Anomalies Frequency Mean  \
count                                 41229.000000   
mean                                      1.084485   
std                                       1.966312   
min                                       0.000000   
25%                                       0.000000   
50%                                       1.000000   
75%                                       1.000000   
max                                      20.000000   

       Temperature Stress Anomalies Degree Heating Weeks  \
count                                       41213.000000   
mean                                            1.204780   
std                                             3.416711   
min                                             0.000000   
25%                                             0.000000   
50%                                             0.000000   
75%                                             1.150000   
max                                            52.450000   

       Temperature Stress Anomalies Degree Heating Weeks Maximum  \
count                                       41229.000000           
mean                                           10.607881           
std                                             6.073912           
min                                             0.000000           
25%                                             6.900000           
50%                                             9.160000           
75%                                            12.310000           
max                                           146.800000           

       Temperature Stress Anomalies Degree Heating Weeks Mean  
count                                       41229.000000       
mean                                            0.590805       
std                                             1.138909       
min                                             0.000000       
25%                                             0.280000       
50%                                             0.400000       
75%                                             0.620000       
max                                            13.150000

In [11]:
for i in numeric_columns:
  df.dropna(subset=[i], inplace=True)

In [15]:
from sklearn.preprocessing import LabelEncoder
Le = LabelEncoder()
for i in ["Ocean_Name", "Country_Name", "Bleaching Comments"]:
  df[i] = Le.fit_transform(df[i])
df.head()

Latitude_Degrees  Longitude_Degrees  Ocean_Name  Country_Name  \
0            23.163           -82.5260           1            20   
1           -17.575          -149.7833           3            31   
2            18.369           -64.5640           1            84   
3            17.760           -64.5680           1            85   
4            17.769           -64.5830           1            85   

   Temperature Stress Anomalies Frequency Max  \
0                                         5.0   
1                                         4.0   
2                                         7.0   
3                                         4.0   
4                                         5.0   

   Temperature Stress Anomalies Frequency Mean  \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

   Temperature Stress Anomalies Degree Heating Weeks  \
0                                               0.00   
1                                               0.26   
2                                               0.00   
3                                               0.00   
4                                               0.00   

   Temperature Stress Anomalies Degree Heating Weeks Maximum  \
0                                               7.25           
1                                               4.65           
2                                              11.66           
3                                               5.64           
4                                               6.89           

   Temperature Stress Anomalies Degree Heating Weeks Mean  Bleaching Comments  
0                                               0.18                        7  
1                                               0.19                        7  
2                                               0.26                        7  
3                                               0.20                        7  
4                                               0.25                        7

In [16]:
from sklearn.model_selection import train_test_split
X = df.iloc[:, 0:9]
Y = df["Bleaching Comments"]
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 42)

In [17]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [18]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(X_train, Y_train)

RandomForestClassifier()

In [19]:
Y_pred = model.predict(X_test)
Y_pred

array([7, 7, 7, ..., 7, 7, 7])

In [20]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print("Model Accuracy:", accuracy_score(Y_test, Y_pred))
print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))
print("Classification Report:\n", classification_report(Y_test, Y_pred))

Model Accuracy: 0.9387358971248332
Confusion Matrix:
 [[   0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    3]
 [   0    0    0    0    1    1    1    1]
 [   1    0    0    0    0    0    0    3]
 [   0    0    1    0   63   12   14  103]
 [   0    0    1    0    9   32   10  176]
 [   0    0    0    0   15   17   23   83]
 [   0    1    1    0   19   23    9 7620]]
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.00      0.00      0.00         3
           2       0.00      0.00      0.00         4
           3       0.00      0.00      0.00         4
           4       0.59      0.33      0.42       193
           5       0.38      0.14      0.20       228
           6       0.40      0.17      0.24       138
           7       0.95      0.99      0.97      7673

    accuracy                           0.94      8243
   macro avg       0.29      0.20  

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_